version: "3.9"
services:
  mongodb:
    image: "mongo:4.4"
    restart: "always"
    volumes:
      - "mongodb_data:/data/db/"
  nodejs:
    build: "."
    volumes:
      - "./:/home/node/"
volumes:
  mongodb_data:
