version: "3.9"
services:
  mongodb:
    image: "mongo:4.4"
    restart: "always"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - "mongodb_data:/data/db/"
volumes:
  mongodb_data:
