version: "3.9"
services:
  mongodb:
    image: "mongo:4.4"
    restart: "always"
    volumes:
      - "mongodb_data:/data/db/"
  nodejs:
    build: "."
    volumes:
      - "./project-config.json:/home/node/project-config.json"
volumes:
  mongodb_data:
